<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;
use App\Models\Subject;

class DataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subjects = [
            ["Living in the IT Era", "GEE 1"],
            ["Readings in Philippine History", "GE 2"],
            ["Art Appreciation", "GE 3"],
            ["Readings in Visual Arts", "GEE 3"],
            ["Purposive Communication", "GE 4"],
            ["The Contemporary World", "GE 5"],
            ["Science and Technology and Society", "GE 6"],
            ["Gender and Society", "GEE 6"],
            ["Mathematics in the Modern World", "GE 7"],
            ["Understanding the Self", "I_GEC 1"],
            ["Ethics", "SC_GE 8"],
            ["Rizal’s Life and Works", "GE 9A"],
            ["Society and Literature", "LIT 1"],
            ["Global Currents & Literature", "LIT 2"],
            ["Kontekstualisadong Kumunikasyon sa Filipino", "FILIPINO 1"],
            ["Filipino sa Ibat-Ibang Disiplina", "FIL 2"],
            ["Physical Activity towards Health Fitness 1", "PE 1"],
            ["Physical Activity towards Health Fitness 2", "PE 2"],
            ["Physical Activity towards Health Fitness 3", "PE 3"],
            ["Movement Enhancement", "PE 1 BA"],
            ["Civic Welfare Training Service 1", "SC_NSTP 1"],
            ["National Service Training Program", "NSTP 2"],
            ["Macro Perspective of Tourism and Hospitality", "THC 101"],
            ["Risk Management as Applied to Safety, Security and Sanitation", "THC 102"],
            ["Quality Service Management in Tourism & Hospitality", "THC 103"],
            ["Philippine Culture and Tourism Geography", "THC 104"],
            ["Micro Perspective of Tourism & Hospitality", "THC 105"],
            ["Tourism & Hospitality Marketing", "THC 106"],
            ["Professional Development & Applied Ethics", "THC 107"],
            ["Multicultural Diversity in Workplace for the Tourism Professional", "THC 108"],
            ["Entrepreneurship in Tourism and Hospitality", "THC 109"],
            ["Applied Business Tools and Technology", "HPC 101"],
            ["Kitchen Essentials and Basic Food Production with Laboratory", "HPC 102"],
            ["Fundamentals in Food Service Operations with Laboratory", "HPC 103"],
            ["Fundamentals in Lodging Operations", "HPC 4A"],
            ["Supply Chain Management in Hospitality Industry", "HPC 105"],
            ["Introduction to Meetings, Incentives, Conferences and Events Management(MICE)", "HPC 106"],
            ["Foreign Language 1 (Mandarin)", "HPC 107"],
            ["Ergonomics & Facilities Planning for the Hospitality Industry", "HPC 108"],
            ["Research in Hospitality 1", "HPC 109"],
            ["Bread and Pastry with Laboratory", "HPE 101"],
            ["Introduction to Transport Service", "HPE 102"],
            ["Bar and Beverage Management with Laboratory", "HPE 103"],
            ["Rooms Divisions and Cost Control with Laboratory", "HPE 104"],
            ["Catering Management with Laboratory", "HPE 106"],
            ["Operations Management in Tourism and Hospitality Industry", "BME 101"],
            ["Strategic Management in Tourism & Hospitality", "BME 102"],
            ["Management & Marketing in 21st Century", "MNGT 101"],
            ["Foundation of Shorthand", "OA 101"],
            ["Keyboarding and Documents Processing", "OA 102"],
            ["Administrative Office Procedures & Management", "OA 103"],
            ["Business Report Writing", "OA 104"],
            ["Advanced Shorthand", "OA 104 B"],
            ["Personal & Professional Development", "OA 105A"],
            ["Business Report Writing", "OA 106"],
            ["Customer Relations", "OA 107B"],
            ["Office Administration Internship", "OA 108"],
            ["Internet Research for Business", "OA 109"],
            ["Machine Shorthand 1", "OA 110"],
            ["Events Management", "OA 110 A"],
            ["Events Management", "OA 111"],
            ["Integrated Software Applications", "OA 112"],
            ["Entrepreneurial Behavior and Competencies", "OA 113"],
            ["Business Law", "OA 114"],
            ["Taxation", "OA 115"],
            ["Legal Office Procedures", "OA ELEC 1"],
            ["Accounting 2", "OA ELEC 2"],
            ["Medical Office Procedures", "OA ELEC 3"],
            ["Filipino Stenography", "OA ELEC 4"],
            ["Web Design", "OA ELEC 5"],
            ["International Studies", "OA ELEC 6"],
            ["Legal/Medical Office", "OA ELEC 7"],
            ["Accounting for Business Enterprise", "ACCTG 101"],
            ["Human Resource Management", "BAC 101"],
            ["Basic Microeconomics", "BAC 102"],
            ["Taxation", "BAC 103"],
            ["International Business and Trade", "BAC 104"],
            ["HRDM Research 1", "BAC 105"],
            ["HRDM Research 2", "BAC 106"],
            ["Administrative and Office Management", "HRDM 101A"],
            ["Recruitment and Selections", "HRDM 102A"],
            ["Compensation Administration", "HRDM 103A"],
            ["Organizational Development", "HRDM 104A"],
            ["Human Behavior in Organization", "MGT 102"],
            ["Obligations and Contracts", "LAW 101"],
            ["Personal Finance", "HRDM ELEC 101A"],
            ["Management Accounting", "HRDM ELEC 102"],
            ["Marketing Management", "HRDM ELEC 103"],
            ["HRDM Research 1", "HRDM ELEC 104A"],
            ["Special Topics in HRDM", "HRDM ELEC 105A"],
            ["Labor Laws and Legislation", "HRDM ELEC 106"],
            ["Introduction to Computing", "CC 101"],
            ["Fundamentals of Programming", "CC 102"],
            ["Intermediate Programming", "CC 103"],
            ["Computer Organization", "CO 101"],
            ["Discrete Mathematics", "MS 101"],
            ["Human Computer Interaction 1", "HCI 101"],
            ["Object Oriented Programming", "OOP 101"],
            ["Human Computer Interaction 2", "HCI 102"],
            ["Multimedia Technologies", "MT 101"],
            ["Networking 1 (Fundamentals of Networking)", "NET 101"],
            ["Information Management 1 (Fundamentals of Database)", "CC 105"],
            ["System Analysis and Design", "SAD 101"],
            ["Web Development 1", "WD 101"],
            ["Application Development and Emerging Technologies", "CC 106"],
            ["Information Management 2", "IM 102"],
            ["Mobile Application Development 1", "MD 101"],
            ["Quantitative Methods", "MS 102"],
            ["Networking 2 (Advanced Networking)", "NET 102"],
            ["Operating Systems Application", "OS 101"],
            ["Social and Professional Issues", "SP 101"],
            ["Web Systems and Technologies 1", "WS 101"],
            ["Capstone Project 2", "CAP 102"],
            ["Elective 3 (Special Topics on Web and Mobile 1)", "ELEC 3"],
            ["Elective 4 (Special Topics on Web and Mobile 2)", "ELEC 4"],
            ["Information Assurance and Security 2", "IAS 102"],
            ["System Administration and Maintenance", "SA 101"],
            ["System Integration and Architecture", "SIA 101"],
            ["Elective 2 (Mobile Application Development 2)", "ELEC 2A"],
            ["Technopreneurship", "TECH 101"],
            ["Elective 1 (Web Systems and Technologies 2)", "ELEC1"],
            ["Information Assurance and Security 1", "IAS 101"],
        ];

        foreach ($subjects as $subject) {
            Subject::create([
                'name' => $subject[0],
                'code' => $subject[1],
            ]);
        }

        $rooms = [
            ['NB 101', 'Academic'],
            ['NB 103', 'Academic'],
            ['NB 104', 'Academic'],
            ['AB 101', 'Academic'],
            ['AB 103', 'Academic'],
            ['AB 104', 'Academic'],
            ['CLR 1', 'Academic'],
            ['CLR 2', 'Academic'],
            ['CLR 3', 'Academic'],
            ['CLR 4', 'Academic'],
            ['CLR 5', 'Academic'],
            ['NB 301', 'Academic'],
            ['NB 302', 'Academic'],
            ['NB 303', 'Academic'],
            ['NB 304', 'Academic'],
            ['FRON ROOM', 'Academic'],
            ['SIMULATION ROOM', 'Academic'],
            ['SUITE ROOM', 'Academic'],
            ['STANDARD ROOM', 'Academic'],
            ['DINING ROOM', 'Academic'],
            ['BAR', 'Academic'],
            ['STOCK ROOM', 'Laboratory'],
            ['BREAD AND PASTRY ROOM', 'Laboratory'],
            ['HOT KITCHEN', 'Laboratory'],
            ['COLD KITCHEN', 'Laboratory']
        ];

        foreach ($rooms as $room) {
            Room::create([
                'room_number' => $room[0],
                'building_number' => $room[1],
            ]);
        }
    }
}
