<?php

return [
    'NB 101' => 'NB 101',
    'NB 103' => 'NB 103',
    'NB 104' => 'NB 104',
    'AB 101' => 'AB 101',
    'AB 102' => 'AB 102',
    'AB 103' => 'AB 103',
    'AB 104' => 'AB 104',
    'CLR 1' => 'CLR 1',
    'CLR 2' => 'CLR 2',
    'CLR 3' => 'CLR 3',
    'CLR 4' => 'CLR 4',
    'CLR 5' => 'CLR 5',
    'NB 301' => 'NB 301',
    'NB 302' => 'NB 302',
    'NB 303' => 'NB 303',
    'NB 304' => 'NB 304',
    'Front Room' => ' Front Room',
    'Simulation Room' => 'Simulation Room',
    'Suite Room' => 'Suite Room',
    'Standard Room' => 'Standard Room',
    'Dining Room' => ' Dining Room',
    'Bar Room' => 'Bar Room',
    'Stock Room' => 'Stock Room',
    'Bread And Pastry Room' => 'Bread And Pastry Room',
    'Hot Kitchen' => 'Hot Kitchen',
    'Cold Kitchen' => 'Cold Kitchen'
];
